### ISSUE TITLE
Change default Media Library grid view from masonry to fitted

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-media#238] opened 2022-05-27 10:55 UTC
Moving @noeltock's suggestion over to the module.

**Currently (Masonry)**

![Screenshot 2021-05-21 at 16 15 31](https://user-images.githubusercontent.com/781166/119335240-69b75d00-bc8c-11eb-87df-fdc1eeeb48b7.png)

Feels like it would be more reasonable to have a **Fitted** setup (tried hacking together via devtools), but goal was:
- Image scales to 90% of thumbnail container with its longest side (be it width or height)
- Remove inner shadow from thumbnail container

![Screenshot 2021-05-24 at 12 41 36](https://user-images.githubusercontent.com/781166/119336089-75efea00-bc8d-11eb-8c8c-70d7a21f0c95.png)

Thoughts?

**Comment by roborourke** [comment] 2022-10-18 08:59
Duplicate of #212

**Closed by roborourke** 2022-10-18 08:59 UTC
